# -*- coding: utf-8 -*-
"""IRWA_Lab001.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-EKYuMhRguuMXs2kMoniQy80F8l4xaof
"""

teams = ["India", "England", "NZ", "Aus"]
captains = ["Kohli", "Root", "Williaamson", "Smith"]

print(list(zip(teams, captains)))
print(dict(zip(teams, captains)))

books = ["textbooks", "exercise books", "story book", "drawing books"]
prices = [100, 60, 90, 70]
quantities = [3, 2, 1, 4]

print(list(zip(books, prices, quantities)))
# print(dict(zip(books, prices, quantities)))

for book, price, quantity in zip(books, prices, quantities):
    total = price * quantity
    print(f"You bought {quantity} {book} for ${total}")

list1 = [2, 4, 6, 8, 10]
result = [x + 10 for x in list1]
print(result)

list1 = [10, 20, 30, 40]
list2 = ["Apples", "Mangoes", "Oranges", "Grapes"]
for a, b in zip(list1, reversed(list2)):
    print(a, b)

list1 = ["a", "b", ["c", ["d", "e", ["f", "g"], "k"], "l"], "m", "n"]
sub_list = ["h", "i", "j"]
list1[2][1][2].extend(sub_list)
print(list1)

list1 = [10, 15, 20, 15, 32, 54, 15]
result = [x for x in list1 if x != 15]
print(result)

dict_1 = {'John': 15, 'Rick': 10, 'Misa': 12}
dict_2 = {'Bonnie': 18, 'Rick': 20, 'Matt': 16}
dict_1.update(dict_2)
print(dict_1)

d = {0: 0, 1: 1, 2: 2, 3: 3}
d[4] = d.pop(0)
print(d)

country = ["USA", "France", "India"]
capital = ["Washington D.C.", "Paris", "New Delhi"]
result = dict(zip(country, capital))
print(result)

My_dict = {
    "Fruit": "Pear",
    "Vegetable": "Carrot",
    "Pet": "Cat",
    "Book": "Moby dick",
    "Crystal": "Amethyst"
}
keysToRemove = ["Book", "Crystal"]
for key in keysToRemove:
    My_dict.pop(key, None)
print(My_dict)

sub_dict = {'math': 100, 'chem': 98, 'sci': 100, 'eng': 100}
key_to_extract = {'math', 'chem', 'sci'}
result = {k: sub_dict[k] for k in key_to_extract}
print(result)

list1 = [12, 15, 32, 42, 55, 75, 122, 132, 150, 180, 200]
result = [x for x in list1 if x % 5 == 0]
print(result)

numbers = [12, 75, 150, 180, 145, 525, 50]
for num in numbers:
    if num > 500:
        break
    if num > 150:
        continue
    if num % 5 == 0:
        print(num)

text = "@W3Resource.Com"
upper = lower = digit = special = 0
for ch in text:
    if ch.isupper():
        upper += 1
    elif ch.islower():
        lower += 1
    elif ch.isdigit():
        digit += 1
    else:
        special += 1
print("Upper case characters:", upper)
print("Lower case characters:", lower)
print("Number case:", digit)
print("Special case characters:", special)

n = 5
num = ''
total = 0
for i in range(n):
    num += '2'
    total += int(num)
    print(num, end='+')
print(f"\nSum of above series is: {total}")