# -*- coding: utf-8 -*-
"""IRWA_Lab03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15VThC4Z-fgOAuIr3jxYUnofEtdP7Wyc3
"""

import os
def build_inv_index(folder_path):
  inv_index = {}
  for file_name in os.listdir(folder_path):
    file_path = os.path.join(folder_path, file_name)
    doc_id = file_name.split('.')[0]

    with open(file_path, 'r', encoding='utf-8') as file:
      content = file.read()
      words = content.split()
      for word in words:
        if word not in inv_index:
          inv_index[word] = []
        if doc_id not in inv_index[word]:
          inv_index[word].append(doc_id)

  return inv_index

folder_path = "/content/drive/MyDrive/inverted"
inv_index = build_inv_index(folder_path)

inv_index

def AND_op(list1,list2):
  return set(list1).intersection(set(list2))

List1 = []
List2 = []

for key in inv_index:
  if key=='schizophrenia':
      List1=inv_index[key]
  if key=='drug':
      List2=inv_index[key]

print(AND_op(List1,List2))

def OR_op(list1,list2):
  return set(list1).union(set(list2))

def NOT_op(a,b):
  return set(b)-set(a)

fileList=[name.split(".")[0] for name in os.listdir(folder_path)]
fileList

List3 = []
List4 = []
List5 = []

for key in inv_index:
  if key=='drug':
      List3=inv_index[key]
  if key=='approach':
      List4=inv_index[key]
  if key=='for':
      List5=inv_index[key]

List6=OR_op(List3,List4)
List7=NOT_op(List6,fileList)
List8=AND_op(List5,List7)
print(List8)

import os
def build_positional_index(folder_path):
  positional_index = {}
  for filename in os.listdir(folder_path):
      file_path = os.path.join(folder_path, filename)
      doc_id = filename.split('.')[0]
      with open(file_path, 'r', encoding='utf-8') as file:
          content = file.read()
          words = content.split()
          for position, word in enumerate(words, start=1):
              if word not in positional_index:
                  positional_index[word] = {}
              if doc_id not in positional_index[word]:
                  positional_index[word][doc_id] = []
              positional_index[word][doc_id].append(position)
  return positional_index

inv_index

folder_path = "/content/drive/MyDrive/positional"

positional_index = build_positional_index(folder_path)

positional_index

